/*
 * This file was generated by dbusidl2cpp version 0.5
 * when processing input file org.kde.amor.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 */

#include "amoradaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class AmorAdaptor
 */

AmorAdaptor::AmorAdaptor(QObject *parent)
   : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

AmorAdaptor::~AmorAdaptor()
{
    // destructor
}

void AmorAdaptor::screenSaverStarted()
{
    // handle method call org.kde.amor.screenSaverStarted
    QMetaObject::invokeMethod(parent(), "screenSaverStarted");

    // Alternative:
    //static_cast<YourObjectType *>(parent())->screenSaverStarted();
}

void AmorAdaptor::screenSaverStopped()
{
    // handle method call org.kde.amor.screenSaverStopped
    QMetaObject::invokeMethod(parent(), "screenSaverStopped");

    // Alternative:
    //static_cast<YourObjectType *>(parent())->screenSaverStopped();
}

void AmorAdaptor::showMessage(const QString &message, int msec)
{
    // handle method call org.kde.amor.showMessage
    QMetaObject::invokeMethod(parent(), "showMessage", Q_ARG(QString, message), Q_ARG(int, msec));

    // Alternative:
    //static_cast<YourObjectType *>(parent())->showMessage(message, msec);
}

void AmorAdaptor::showTip(const QString &tip)
{
    // handle method call org.kde.amor.showTip
    QMetaObject::invokeMethod(parent(), "showTip", Q_ARG(QString, tip));

    // Alternative:
    //static_cast<YourObjectType *>(parent())->showTip(tip);
}


#include "amoradaptor.moc"
