/*
 * This file was generated by dbusidl2cpp version 0.5
 * when processing input file org.kde.amor.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 */

#ifndef AMORADAPTOR_H_214771149771079
#define AMORADAPTOR_H_214771149771079

#include <QtCore/QObject>
#include <dbus/qdbus.h>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.kde.amor
 */
class AmorAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.amor")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.amor\" >\n"
"    <method name=\"showTip\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"tip\" />\n"
"    </method>\n"
"    <method name=\"showMessage\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"message\" />\n"
"      <arg direction=\"in\" type=\"i\" name=\"msec\" />\n"
"    </method>\n"
"    <method name=\"screenSaverStopped\" />\n"
"    <method name=\"screenSaverStarted\" />\n"
"  </interface>\n"
        "")
public:
    AmorAdaptor(QObject *parent);
    virtual ~AmorAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void screenSaverStarted();
    void screenSaverStopped();
    void showMessage(const QString &message, int msec);
    void showTip(const QString &tip);
Q_SIGNALS: // SIGNALS
};

#endif
